version: '3.3'
services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: euphron_frontend
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
