volumes:
    node_modules:
services:
    app_dev:
        container_name: euphron_frontend_dev
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        ports:
            - '3000:3000'
            - '24678:24678'
        volumes:
            - .:/src
            - node_modules:/src/node_modules
    app:
        container_name: euphron_frontend
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - '3000:3000'